In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [142]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
i = np.random.rand(10,5)
i[:,-1] = np.random.randint(2 ,size = 10)
i

array([[0.02812537, 0.50517756, 0.29812612, 0.3420438 , 1.        ],
       [0.74060024, 0.0276792 , 0.12482736, 0.60457103, 0.        ],
       [0.67241486, 0.59836057, 0.68437234, 0.68025313, 1.        ],
       [0.41222596, 0.38398173, 0.46023597, 0.04539477, 0.        ],
       [0.95302438, 0.9929198 , 0.45393924, 0.90237665, 0.        ],
       [0.57379636, 0.4675025 , 0.25023069, 0.70741983, 1.        ],
       [0.99816253, 0.01908674, 0.24683393, 0.84858973, 0.        ],
       [0.87273209, 0.1717611 , 0.04043304, 0.48493336, 0.        ],
       [0.2824867 , 0.68858124, 0.81457427, 0.28152268, 1.        ],
       [0.12538681, 0.71996828, 0.30178332, 0.95795727, 1.        ]])

In [113]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
idx.remove(5)
np_matrix[idx,:]

array([[0.03266444, 0.08647276, 0.43439372, 0.91830535, 0.2266202 ],
       [0.22009064, 0.72880608, 0.67701462, 0.64719608, 0.47224328],
       [0.17226336, 0.96253483, 0.50589105, 0.56401358, 0.38614933],
       [0.59511381, 0.6888211 , 0.83014447, 0.28632326, 0.94067682]])

In [141]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

mtrix = np.random.randint(10 , size=(10,5))
label = np.random.randint(2, size = (10))
train_data = mtrix[np.where(label == 0)]
test_data = mtrix[np.where(label == 1)]
print ("mtrix" + "\n" + str(mtrix) + "\n" + "\n" 
       + "label" + "\n" + str(label) + "\n" + "\n"
       + "train_data" + "\n" + str(train_data) + "\n" + "\n"
       + "test_data" + "\n" + str(test_data) + "\n")


mtrix
[[7 0 7 9 2]
 [5 8 9 3 3]
 [9 9 9 7 0]
 [1 6 9 8 0]
 [6 4 5 2 6]
 [5 3 1 2 3]
 [2 1 1 2 3]
 [1 7 6 3 0]
 [1 0 3 6 9]
 [2 1 7 8 6]]

label
[0 0 0 0 1 1 1 0 1 0]

train_data
[[7 0 7 9 2]
 [5 8 9 3 3]
 [9 9 9 7 0]
 [1 6 9 8 0]
 [1 7 6 3 0]
 [2 1 7 8 6]]

test_data
[[6 4 5 2 6]
 [5 3 1 2 3]
 [2 1 1 2 3]
 [1 0 3 6 9]]



In [128]:
import numpy as np

In [11]:
!pip install numpy

> ***การเขียนโปรแกรมต่างๆ เลข version สำคัญมากๆ เพราะบางทีเราไปเอาโค้ดคนอื่นมาใช้ อาจจะใช้คนละเวอร์ชั่นกับที่เรามี***

In [12]:
np.__version__

'1.19.5'

**Vector or 1D Array**

In [13]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

**Matrix or 2D Array**

In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a=np.array([1,2,3,4,5,6,7])
a[0]

1

In [105]:
np_matrix = np.random.rand(5,5)
np_matrix

array([[0.2532871 , 0.75343251, 0.65463561, 0.74531624, 0.04646497],
       [0.03266444, 0.08647276, 0.43439372, 0.91830535, 0.2266202 ],
       [0.22009064, 0.72880608, 0.67701462, 0.64719608, 0.47224328],
       [0.17226336, 0.96253483, 0.50589105, 0.56401358, 0.38614933],
       [0.59511381, 0.6888211 , 0.83014447, 0.28632326, 0.94067682]])

In [77]:
a[2:5]

array([3, 4, 5])

In [78]:
l=[1,2,3,4,5,6,7]
l[0]

1

In [79]:
l[2:5]

[3, 4, 5]

In [80]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [81]:
l[:6]

[1, 2, 3, 4, 5, 6]

In [82]:
a[3:]

array([4, 5, 6, 7])

In [ ]:
l[3:]

In [ ]:
a[-3]

In [ ]:
l[-1]

In [ ]:
a[2:-3]

In [152]:
l[2:-3]

[3, 4]

In [151]:
a[-5:]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
a[-5:-1]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
a[-2:2]

array([], shape=(0, 5), dtype=float64)

In [147]:
np.size(a)

25

In [145]:
np.shape(a)

(5, 5)

In [ ]:
l[l[3]]

In [ ]:
l.reverse()
l

In [ ]:
sorted(a, reverse = True)

In [18]:
np.shape(a)

(7,)

In [ ]:
a=a.reshape(1,7)
np.shape(a)

In [ ]:
a

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
l=([1,2,3],[4,5,6],[7,8,9])

In [ ]:
a[0,0]

In [ ]:
l[0][0]

In [ ]:
a[1,:]

In [ ]:
l[1][:]

In [ ]:
l[1]

In [ ]:
a[:,-1]

In [ ]:
l[:][-1]

In [ ]:
a[:,1]=0
a

In [ ]:
a[1,:]=0
a

In [ ]:
a[0:2,:]=8
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
np.size(a,0)

In [ ]:
np.ndim(a)

In [19]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [30]:
a = np.array(np_mix_matrix[:,1], dtype = int)
a

array([2, 4, 6])

In [29]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [143]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [33]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [35]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [ ]:
np.sqrt(np.ones((5,5))*9)

In [ ]:
np.empty([15,15])

**เลขที่สุ่มออกมาจะอยู่ในช่วงระหว่าง 0-1**

In [51]:
np.random.rand()

0.7265555974224593

In [22]:
np.random.rand()*10

9.477728926998644

In [23]:
[np.round(np.random.rand()*10) for item in range(10)]

[7.0, 10.0, 8.0, 4.0, 2.0, 8.0, 7.0, 9.0, 2.0, 3.0]

In [24]:
np.random.randint(5)

0

In [ ]:
[np.random.randint(5) for item in range(10)]

In [ ]:
np.random.seed(0)
[np.random.randint(5) for item in range(10)]

In [ ]:
np.random.seed(2)
np.random.randint(2,5)

In [ ]:
np.random.rand(5,5)

In [ ]:
np.round(np.random.rand(5,5))

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

**Random Data 1257 rows each row has 5 columns**

In [ ]:
np_matrix = np.round(np.random.rand(1257,5))
np_matrix

**Random 85 from 1257 Datas**

In [ ]:
idx_choose = np.random.choice(1257,85, replace = False)
idx_choose

In [ ]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

In [ ]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

In [53]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 2, 1, 2, 0],
       [0, 1, 2, 0, 1],
       [1, 0, 1, 2, 2],
       [1, 2, 0, 0, 2],
       [0, 1, 2, 2, 1]])

In [54]:
row,column = np.where(np_matrix == 2)
[(row[i],column[4]) for i in range(len(row))]

[(0, 1), (0, 3), (1, 2), (2, 3), (2, 4), (3, 1), (3, 4), (4, 2), (4, 3)]

In [62]:
np_matrix[0,4]

0

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

In [ ]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

In [ ]:
rng = np.random.RandomState(0)
rng.rand()

In [ ]:
rng = np.random.RandomState(0)
[np.round(rng.rand()*10) for item in range(10)]

In [ ]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

In [ ]:
result = (np_matrix == 2)
result

In [ ]:
np_matrix[result] = 99
np_matrix

In [ ]:
np_matrix[np_matrix == 2] = 99
np_matrix